// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1QbyZQgpBBerwnjjkWEyiVW9BbuPJ4SA',
    appId: '1:337332431930:web:36b44dd06e18b9013c9903',
    messagingSenderId: '337332431930',
    projectId: 'commutrdriverapp-a0ff3',
    authDomain: 'commutrdriverapp-a0ff3.firebaseapp.com',
    storageBucket: 'commutrdriverapp-a0ff3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaA9VRh8L_SfLZR6aOwUBgPlZXTXz4wGM',
    appId: '1:337332431930:android:a44c1450389354a43c9903',
    messagingSenderId: '337332431930',
    projectId: 'commutrdriverapp-a0ff3',
    storageBucket: 'commutrdriverapp-a0ff3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzeCBNafx5fFd23qVDHIEE56DHiLb_gLQ',
    appId: '1:337332431930:ios:b9561e3f7a0926923c9903',
    messagingSenderId: '337332431930',
    projectId: 'commutrdriverapp-a0ff3',
    storageBucket: 'commutrdriverapp-a0ff3.firebasestorage.app',
    iosBundleId: 'com.user.commutr',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzeCBNafx5fFd23qVDHIEE56DHiLb_gLQ',
    appId: '1:337332431930:ios:b9561e3f7a0926923c9903',
    messagingSenderId: '337332431930',
    projectId: 'commutrdriverapp-a0ff3',
    storageBucket: 'commutrdriverapp-a0ff3.firebasestorage.app',
    iosBundleId: 'com.user.commutr',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1QbyZQgpBBerwnjjkWEyiVW9BbuPJ4SA',
    appId: '1:337332431930:web:c8cd5a26041cc4e73c9903',
    messagingSenderId: '337332431930',
    projectId: 'commutrdriverapp-a0ff3',
    authDomain: 'commutrdriverapp-a0ff3.firebaseapp.com',
    storageBucket: 'commutrdriverapp-a0ff3.firebasestorage.app',
  );
}
